spring.application.name=Spring-Boot-Web-Application
logging.level.org.springframework.web=DEBUG
#These properties configure Spring MVC to resolve view names to JSP files located in /WEB-INF/jsp/ with the .jsp extension. For example, a view name welcome will map to /WEB-INF/jsp/welcome.jsp.
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
logging.level =INFO